### ISSUE TITLE
any pretrained models?

### ISSUE THREAD

**Issue by lucasjinreal** [Jung-Jun-Uk/UNPG#3]
any pretrained models?

**Comment by junuke** [comment]
Yes! There is a link to the pre-trained model in the table.

**Comment by lucasjinreal** [comment]
@Jung-Jun-Uk thank u for the reply. Does there any mobilefacenet (or small models) avaiable? I saw it all seems at least r34 big model. 

I wanna face recognition cost to minimal  less than 10ms on CPU.

**Comment by junuke** [comment]
No, we don't have but you can train our method with a small model.
