### ISSUE TITLE
the megaface identification code

### ISSUE THREAD

**Issue by ohtiger** [Jung-Jun-Uk/UNPG#4]
could you please release the code of megaface identification

**Comment by junuke** [comment]
Megface is a challenge, so we can't know exactly which images are tested and how. That is why I gave up on reproducing the code. Instead, see this link ( https://github.com/deepinx/megaface-evaluation) here. I replaced mxnet with torch and then tested megaface. I think there were some errors, but I don't remember now. you can fix it to googling.
