### ISSUE TITLE
pretrained된 모델의 학습 데이터셋이 어떻게 되나요?

### ISSUE THREAD

**Issue by TallyH0** [Jung-Jun-Uk/UNPG#5]
레포에서 제공하는 pretrained 모델의 train dataset이 어떻게 되나요?

MS1MV2인지 AIHUB korea face까지 모두 학습한건지 궁금합니다.

**Comment by junuke** [comment]
MS1MV2와 K-FACE 각각 학습되었습니다. 둘 다 학습 데이터로 사용하지는 않았습니다.
