### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'items'

### ISSUE THREAD

**Issue by BeiningWu** [Jung-Jun-Uk/UNPG#8]
When I run the train command as follow, there is an erroe occured.
`python train.py --model 'iresnet-50' --head 'arcface' --aux 'unpg' --data 'data/face.yaml' --hyp 'data/hyp.
yaml' --name 'example' --device 0,1`
Traceback (most recent call last):
  File "/home/wbn/UNPG/recognition/train.py", line 263, in <module>
    main(opt, device)
  File "/home/wbn/UNPG/recognition/train.py", line 128, in main
    train(opt, model, headandloss, optimizer, scheduler, train_dataset.loader, device, opt.global_rank)                
  File "/home/wbn/UNPG/recognition/train.py", line 176, in train
    for key, val in metas.items():            
AttributeError: 'Tensor' object has no attribute 'items'

The error happens there:
```python
for key, val in metas.items():            
            meta_dict[key].update(val.item(), labels.size(0))
```
> https://github.com/Jung-Jun-Uk/UNPG/blob/main/recognition/train.py#L176-L177

it seems that `headandloss` should return a dict but return a tensor

**Comment by junuke** [comment]
Thank you for your comment. First of all, as a simple solution, since meta_dict is just a meta information log, simply comment it out as below and proceed with training. I will modify code later.

```python
        # for key, val in metas.items():            
        #    meta_dict[key].update(val.item(), labels.size(0))
        losses.update(loss.item(), labels.size(0))        

        if (i+1) % opt.print_freq == 0 and rank in [-1, 0]:
            elapsed = str(datetime.timedelta(seconds=round(time.time() - start_time)))
            start_time = time.time()            
            s = ''
            # for key, val in meta_dict.items():
            #    s += key + ' {:.6f} ({:.6f}) '.format(val.val, val.avg)
            print("Batch {}/{}\t Loss {:.6f} ({:.6f}), {} elapsed time (h:m:s): {}" \
                .format(i+1, len(trainloader), losses.val, losses.avg, s, elapsed))
          
        if opt.local_test and (i+1) % opt.eval_freq == 0 and rank in [-1, 0]:
            acc = evals(opt.data_cfg, opt.save_dir, model, opt.test_dataset, device, train=True)            
            model.train()
```

**Comment by junuke** [comment]
It seems to be duplicated with the previous experimental code that included meta information in headandloss. Please comment out the code below as well. Thank you.

```python
with torch.cuda.amp.autocast():
            deep_features = model(data)                        
            # loss, metas = headandloss(deep_features, labels, rank)
            loss = headandloss(deep_features, labels, rank)
```

**Comment by BeiningWu** [comment]
Thank you very much for your reply.
The error has been completely fixed!
